### ISSUE TITLE
Commenting Guidelines | 4arc3

### ISSUE THREAD

**Issue by 4arc3** [4arc3/4arc3.github.io#3]
https://4arc3.github.io/2020/07/23/commenting-guidelines.html 

 
     converging to farce

**Comment by df235** [comment]
pros and cons of (hierarchical) comments #TODO

**Comment by 4arc3** [comment]
![404](https://user-images.githubusercontent.com/63576140/88249823-1e5fa700-cc95-11ea-9837-1cc5a5e98f2b.jpg)
Bye
